### ISSUE TITLE
Error occurred while creating public link (using NC 20)

### ISSUE THREAD

**Issue by PatriceVigier** [jimmyl0l3c/cfg_share_links#45]
Nextcloud 20.05
Configurable Share Links 1.2.2
-When I create a custom link for a directory I get the message "Error occurred while creating public link" and no links are shown
![image](https://user-images.githubusercontent.com/42541035/167117078-615eadea-2403-48b7-87a4-6c0a1eb839e1.png)
-If I leave the directory and come back to it, the created custom share is shown on the normal "share link"
![image](https://user-images.githubusercontent.com/42541035/167116417-4692e5bd-f007-4149-9628-e2e272a8e4b4.png)
-In the end the custom link is created and works.
It looks like it is a refresh display, unless links should be shown under the "Custom links" line

**Comment by jimmyl0l3c** [comment]
Hi, 
sorry for the delayed answer,

firstly just a clarification - custom public links are always shown like "normal share links". I'm using the core sharing functionality to create them with minor difference of specifying share tokens (and optionally setting labels). This part is normal and expected behavior.

So the problem is probably with reloading the data after creating the link. I'll look into it, but I can't promise quick fix, because update for NC 24 has priority. I'd suggest updating Nextcloud to at least 22, because versions 20 and 21 are not supported anymore.

**Comment by PatriceVigier** [comment]
Hello,
Thank you for your answer.
I cannot update right now but I will and let you know.
Thank you for your time.

**Comment by jimmyl0l3c** [comment]
This bug seems to occur only when using old versions of Nextcloud.

Nextcloud doesnt support those versions anymore and using them migh be a security risk due to missing security patches. So it doesnt make much sense to spend time on this to try to fix it.
