### ISSUE TITLE
Custom link not working when Enforce Password Protection Activated

### ISSUE THREAD

**Issue by unaipuelles** [jimmyl0l3c/cfg_share_links#49]
Hi, I just installed the app and I started testing it. While I was creating a custom link one error appeared. The problem is when I create a custom link the next error message appears:
<img width="410" alt="Screenshot 2022-05-25 at 01 03 16" src="https://user-images.githubusercontent.com/32477616/170145922-6557c914-2d76-4c15-a260-c8e235c760d1.png">
I tried generating the link with the password and then creating the custom one but same error appears. I think this is because I have the "Enforce Password Protection" activated. 

In relation, it would be nice after creating the default sharing link with the password edit the actual share link to your own customized text (I don't know if the core of NextCloud admits editing the sharing link).

If you need more information, do not doubt telling me.

Thank you in advance,
__
Unai Puelles

**Comment by jimmyl0l3c** [comment]
Hi, thank you for reporting this issue. It is most likely due to the "Enforce Password Protection" option. I didn't test the app with this option enabled. I'll look into it but, I won't have time sooner than in the beginning of next month.

As a workaround is it possible to generate the link with the password and change the link after that? ([Renaming the existing link](https://github.com/jimmyl0l3c/cfg_share_links/blob/master/screens/nc03.png))

**Comment by thetuxinator** [comment]
Running in to the same issue

**Comment by jimmyl0l3c** [comment]
The issue should be fixed in the [latest version](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v2.0.1). Let me know if you run into any problems.

And sorry for the long wait.
